### ISSUE TITLE
Utilize the X_cili_Screen_NameX variable to name screens

### ISSUE THREAD

**Issue by MikeMcCall** [cesarfelip3/facilitate#10]
We have attempted to implement the X_cili_Screen_NameX X variable. for use in the screen headers. The way it is intended to work is to replace the first occurrence of the string X_cili_Screen_NameX variable with a unique description of each screen. As an example in the screen shot below, if the X_cili_Screen_NameX were used in the blue bar at the top in the area in yellow then on this screen it should be replaced by **User Profile List.**  
![image](https://cloud.githubusercontent.com/assets/18315465/14449123/b384b11e-0024-11e6-9805-c9cdbf6d87f2.png)

The names for each screen can be customized in the language profile section named "Express Facilitator Additional Topic Mode Options / Alert Formats, Messages & Screen Names."  See the screen shot below: 
![image](https://cloud.githubusercontent.com/assets/18315465/14449153/f861fc92-0024-11e6-889b-c443fcef930d.png)

The accepted values for this field as of now are below but more can be added in the future.

SCREEN NAMES
Screen-Name-Simple-Vote=Simple Vote
Screen-Name-Brainstorm=Brainstorm
Screen-Name-Brainstorm Comment=Brainstorm Commenting
Screen-Name-Edit Topic=Edit Topic Settings
Screen-Name-Brainstorm-QuickCat=Brainstorm Quick Cat
Screen-Name-Default=Cilistorm
Screen-Name-Main-Screen=Main Screen
Screen-Name-User-Profile-List=User Profile List
Screen-Name-Edit-User-Profile=Edit User Profile
Screen-Name-Voting-Profile-List=Voting Profile List
Screen-Name-Edit-Voting-Profile=Edit Voting Profile
Screen-Name-Custom-Screen-Template-List=Custom Screen Template List
Screen-Name-Edit-Custom-Screen-Template=Edit Custom Screen Template
Screen-Name-Conference-Manager-List=Conference Manager List
Screen-Name-Conference-Manager-Topic-List=Conference Manager Topic List
Screen-Name-Conference-Editor=Conference Editor
Screen-Name-Topic-Editor=Topic Editor
Screen-Name-Subtopic-Editor=Subtopic Editor
Screen-Name-Broadcast=Broadcast Message
Screen-Name-Who-Is-On=Who Is On
Screen-Name-Show Stats=Show System Stats
Screen-Name-Language-Profile-List=Language Profile List
Screen-Name-Edit-Language-Profile=Edit Language Profile
Screen-Name-Licensing-Info=Licensing Information
END OF SCREEN NAMES

**Comment by aneeshjoseph** [comment]
Updated the screens with the title. please check the same.

**Comment by MikeMcCall** [comment]
Perfect! Thanks
