### ISSUE TITLE
need edit in the source code

### ISSUE THREAD

**Issue by aneeshjoseph** [cesarfelip3/facilitate#11]
1. There is a <p> tag wrapped on the "Edit Language Profile" table. Please see the screen shot 1 below:

**screen shot 1**
![101](https://cloud.githubusercontent.com/assets/5081843/14472182/75756b50-009e-11e6-82a8-7581c88df8f9.jpg)

2. Expand Collapse section need to wrap with div in the "Conference Editor" pages

@MikeMcCall

**Comment by MikeMcCall** [comment]
The extra paragraph tag has been removed. Let me know if you need anything else on this screen.
