### ISSUE TITLE
 Custom Screen Template Search Screen & Custom Screen Template Editor Screens - Clean Up

### ISSUE THREAD

**Issue by MikeMcCall** [cesarfelip3/facilitate#6]
The Screens associated with the Custom Screen Template option found in the side bar need to be styled and cleaned up. There are two primary screens associated with this capability. They are named and a portion of each is included below. 

The top section for the Search screen needs to be made to look more professional and consistent with the new look. The source for the top area of this screen can be completely edited using the appropriate field found in the Language Profile. _Please note that these areas may include X variables which are essential to the working of the screens and they most be used._

For the Custom Screen Template Search Screen you will find a red insert with the field in the Language Profile which controls that portion of the screen. Please note that all aspects of the screens need to be examined and cleaned up, not just the top section.

In addition we will assign a new class on the Custom Screen Template Screen for the name of the Custom Screen Template screen so that can more easily be styled.

**Custom Screen Template Search List and Search Screen.**
![image](https://cloud.githubusercontent.com/assets/18315465/14362612/26c46ca0-fcb5-11e5-93ae-8b28161a0f11.png)

**Custom Screen Template Editor Screen**
![image](https://cloud.githubusercontent.com/assets/18315465/14362617/2e3c6f28-fcb5-11e5-96bb-eb2269e85ce6.png)

**Comment by aneeshjoseph** [comment]
I have updated. Please check the screens..

**Comment by MikeMcCall** [comment]
Thanks. This screen is looking much better. Two small issues. The first is that the label for the first text entry field, "Custom Main Screen," is not left justified (see the attached screenshot - first area in yellow). In the same screenshot, the space above each of the text areas is minimal (as an example see the second area in yellow in the screenshot. Would it be possible to provide a little bit more space between each label and the text entry area above it?  Thanks,

Screenshot:
![image](https://cloud.githubusercontent.com/assets/18315465/14391773/ea025d0e-fd72-11e5-8c54-8be4880b82ec.png)

**Comment by aneeshjoseph** [comment]
Updated... Please check the same

**Comment by MikeMcCall** [comment]
Thanks. That is what I was looking for. Thanks again.

**Comment by aneeshjoseph** [comment]
Please check the updated page...

**Comment by MikeMcCall** [comment]
Can we use a consistent look for all of these tables? The area in yellow in the screenshot below from the User Profile screen would seem like a good look to standardize on. The blue table header and alternating row background colors and the use of inner table borders. Does that make sense and would it be fairly straight forward?

![image](https://cloud.githubusercontent.com/assets/18315465/14545457/0661d296-0254-11e6-9939-a9a3190c9a52.png)

**Comment by aneeshjoseph** [comment]
please check the updated screens

**Comment by MikeMcCall** [comment]
This screen looks fine. I think I do like the approach of just going with the blue bar at the top of the Table Header Row instead of making the background blue (see screenshot 1 versus screenshot 2).

The List screen is looking good. I assume you're still working on the Editor Screens

Screenshot 1
![image](https://cloud.githubusercontent.com/assets/18315465/14567231/0c69b570-02e8-11e6-99af-bdeef800442a.png)

Screenshot 2
![image](https://cloud.githubusercontent.com/assets/18315465/14567241/1e4b6388-02e8-11e6-89e5-6d764fe908ad.png)

**Comment by aneeshjoseph** [comment]
So you mean to change the blue header background to white?

**Comment by MikeMcCall** [comment]
I apologize but on second thought, I believe it makes more sense to have all of the header backgrounds for all of the screens with Lists in blue. That makes them standout more.

**Comment by MikeMcCall** [comment]
I am a little conflicted on which looks better. Is it relatively easy to make it so we can change that for all of these tables easily in one place?
