### ISSUE TITLE
Please update Expand Collapse image in the accordion section

### ISSUE THREAD

**Issue by aneeshjoseph** [cesarfelip3/facilitate#8]
Please update Expand Collapse image in the accordion section. please find the attached images @MikeMcCall 
![collapse](https://cloud.githubusercontent.com/assets/5081843/14430536/79ab0cb6-ffae-11e5-92f9-fdd304f7baf1.png)
![expand](https://cloud.githubusercontent.com/assets/5081843/14430537/79afd246-ffae-11e5-83ee-098cd1e7272e.png)

please see the accordion sample
![accordian-sample](https://cloud.githubusercontent.com/assets/5081843/14430649/ee857558-ffae-11e5-9f37-26920ffcab08.jpg)

Also can you please add a class to the help icon in the accordion section[ please check the screenshot attaches **class-to-help-icon.jpg ** ]
![class-to-help-icon](https://cloud.githubusercontent.com/assets/5081843/14430766/557323aa-ffaf-11e5-860d-57bc75b32f91.jpg)

**Comment by MikeMcCall** [comment]
We believe we have updated all of the necessary files. Please note that there were several .js files while we have copied from the Web root directory to the js subdirectory within the cilistorm directory. The original files in the Web root directory are associated with the Legacy interface and still use the .gif formatted icons. The copies moved to the Web\cilistorm\js directory are the ones which should be used by the cilistorm interface. The three files are shown in the screenshot below: 
![image](https://cloud.githubusercontent.com/assets/18315465/14447202/2652e16a-0012-11e6-91a1-16bbaf08993c.png)

The Language Profile needed to be updated to reflect the new location for cilistorm leaders. 
![image](https://cloud.githubusercontent.com/assets/18315465/14447257/9a49df7e-0012-11e6-8958-f70fc0ac1d90.png)

We have done that for the basic leader and the pro leaders on the cilistorm.Facilitate.com site.

Also the new placement will allow you to update these files directly if you wish for cilistorm users.
